import { prisma } from "@/lib/prisma";
import { headers } from "next/headers";
import { Prisma } from "@prisma/client";

interface AuditLogParams {
  userId: string;
  action: string;
  entityType: string;
  entityId?: string;
  details?: Record<string, unknown>;
}

export async function createAuditLog({
  userId,
  action,
  entityType,
  entityId,
  details,
}: AuditLogParams) {
  try {
    const headersList = headers();
    const ipAddress =
      headersList.get("x-forwarded-for")?.split(",")[0] ||
      headersList.get("x-real-ip") ||
      "unknown";
    const userAgent = headersList.get("user-agent") || "unknown";

    await prisma.auditLog.create({
      data: {
        userId,
        action,
        entityType,
        entityId,
        details: details as Prisma.InputJsonValue,
        ipAddress,
        userAgent,
      },
    });
  } catch (error) {
    console.error("Failed to create audit log:", error);
    // Don't throw - audit logging should not break the main operation
  }
}

export const AuditActions = {
  // User actions
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_MFA_ENABLED: "USER_MFA_ENABLED",
  USER_MFA_DISABLED: "USER_MFA_DISABLED",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_APPROVED: "USER_APPROVED",
  USER_REJECTED: "USER_REJECTED",

  // Facility application actions
  FACILITY_APPLICATION_SUBMITTED: "FACILITY_APPLICATION_SUBMITTED",
  FACILITY_APPLICATION_APPROVED: "FACILITY_APPLICATION_APPROVED",
  FACILITY_APPLICATION_REJECTED: "FACILITY_APPLICATION_REJECTED",

  // Facility actions
  FACILITY_CREATED: "FACILITY_CREATED",
  FACILITY_UPDATED: "FACILITY_UPDATED",
  FACILITY_DELETED: "FACILITY_DELETED",

  // Intake actions
  INTAKE_DRAFT_SAVED: "INTAKE_DRAFT_SAVED",
  INTAKE_DRAFT_ARCHIVED: "INTAKE_DRAFT_ARCHIVED",
  INTAKE_DRAFT_RESTORED: "INTAKE_DRAFT_RESTORED",
  INTAKE_SUBMITTED: "INTAKE_SUBMITTED",
  INTAKE_UPDATED: "INTAKE_UPDATED",
  INTAKE_APPROVED: "INTAKE_APPROVED",
  INTAKE_CONDITIONAL: "INTAKE_CONDITIONAL",
  INTAKE_DENIED: "INTAKE_DENIED",
  INTAKE_PDF_DOWNLOADED: "INTAKE_PDF_DOWNLOADED",
  INTAKE_DISCHARGED: "INTAKE_DISCHARGED",
  INTAKE_READMIT_CREATED: "INTAKE_READMIT_CREATED",

  // Document actions
  DOCUMENT_REQUESTED: "DOCUMENT_REQUESTED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_APPROVED: "DOCUMENT_APPROVED",
  DOCUMENT_VIEWED: "DOCUMENT_VIEWED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",
  DOCUMENT_UPDATED: "DOCUMENT_UPDATED",

  // Credential actions
  CREDENTIAL_UPLOADED: "CREDENTIAL_UPLOADED",
  CREDENTIAL_UPDATED: "CREDENTIAL_UPDATED",
  CREDENTIAL_DELETED: "CREDENTIAL_DELETED",

  // Message actions
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_READ: "MESSAGE_READ",

  // Employee actions
  EMPLOYEE_CREATED: "EMPLOYEE_CREATED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  EMPLOYEE_DEACTIVATED: "EMPLOYEE_DEACTIVATED",

  // Employee document actions
  EMPLOYEE_DOCUMENT_UPLOADED: "EMPLOYEE_DOCUMENT_UPLOADED",
  EMPLOYEE_DOCUMENT_UPDATED: "EMPLOYEE_DOCUMENT_UPDATED",
  EMPLOYEE_DOCUMENT_DELETED: "EMPLOYEE_DOCUMENT_DELETED",

  // Employee document type actions
  EMPLOYEE_DOC_TYPE_CREATED: "EMPLOYEE_DOC_TYPE_CREATED",
  EMPLOYEE_DOC_TYPE_UPDATED: "EMPLOYEE_DOC_TYPE_UPDATED",
  EMPLOYEE_DOC_TYPE_DELETED: "EMPLOYEE_DOC_TYPE_DELETED",

  // Meeting actions
  MEETING_CREATED: "MEETING_CREATED",
  MEETING_UPDATED: "MEETING_UPDATED",
  MEETING_CANCELLED: "MEETING_CANCELLED",
  MEETING_STARTED: "MEETING_STARTED",
  MEETING_ENDED: "MEETING_ENDED",

  // ASAM Assessment actions
  ASAM_DRAFT_SAVED: "ASAM_DRAFT_SAVED",
  ASAM_DRAFT_ARCHIVED: "ASAM_DRAFT_ARCHIVED",
  ASAM_DRAFT_RESTORED: "ASAM_DRAFT_RESTORED",
  ASAM_SUBMITTED: "ASAM_SUBMITTED",
  ASAM_UPDATED: "ASAM_UPDATED",
  ASAM_APPROVED: "ASAM_APPROVED",
  ASAM_CONDITIONAL: "ASAM_CONDITIONAL",
  ASAM_DENIED: "ASAM_DENIED",
  ASAM_PDF_DOWNLOADED: "ASAM_PDF_DOWNLOADED",

  // Fire Drill Report actions
  FIRE_DRILL_SUBMITTED: "FIRE_DRILL_SUBMITTED",
  FIRE_DRILL_UPDATED: "FIRE_DRILL_UPDATED",
  FIRE_DRILL_DELETED: "FIRE_DRILL_DELETED",
  FIRE_DRILL_PDF_DOWNLOADED: "FIRE_DRILL_PDF_DOWNLOADED",

  // Evacuation/Disaster Drill Report actions
  EVACUATION_DRILL_SUBMITTED: "EVACUATION_DRILL_SUBMITTED",
  EVACUATION_DRILL_UPDATED: "EVACUATION_DRILL_UPDATED",
  EVACUATION_DRILL_DELETED: "EVACUATION_DRILL_DELETED",
  EVACUATION_DRILL_PDF_DOWNLOADED: "EVACUATION_DRILL_PDF_DOWNLOADED",

  // Oversight Training Report actions
  OVERSIGHT_TRAINING_SUBMITTED: "OVERSIGHT_TRAINING_SUBMITTED",
  OVERSIGHT_TRAINING_DELETED: "OVERSIGHT_TRAINING_DELETED",

  // Email actions
  ENROLLMENT_EMAIL_SENT: "ENROLLMENT_EMAIL_SENT",
  EMPLOYEE_EMAIL_SENT: "EMPLOYEE_EMAIL_SENT",

  // ART Meeting actions
  ART_MEETING_CREATED: "ART_MEETING_CREATED",
  ART_MEETING_UPDATED: "ART_MEETING_UPDATED",
  ART_MEETING_SUBMITTED: "ART_MEETING_SUBMITTED",
  ART_MEETING_SKIPPED: "ART_MEETING_SKIPPED",
  ART_MEETING_DELETED: "ART_MEETING_DELETED",

  // Discharge Summary actions
  DISCHARGE_SUMMARY_CREATED: "DISCHARGE_SUMMARY_CREATED",
  DISCHARGE_SUMMARY_UPDATED: "DISCHARGE_SUMMARY_UPDATED",
  DISCHARGE_SUMMARY_SUBMITTED: "DISCHARGE_SUMMARY_SUBMITTED",
  DISCHARGE_SUMMARY_DELETED: "DISCHARGE_SUMMARY_DELETED",
  DISCHARGE_SUMMARY_PDF_DOWNLOADED: "DISCHARGE_SUMMARY_PDF_DOWNLOADED",

  // Incident Report actions
  INCIDENT_REPORT_CREATED: "INCIDENT_REPORT_CREATED",
  INCIDENT_REPORT_UPDATED: "INCIDENT_REPORT_UPDATED",
  INCIDENT_REPORT_SUBMITTED: "INCIDENT_REPORT_SUBMITTED",
  INCIDENT_REPORT_DELETED: "INCIDENT_REPORT_DELETED",
  INCIDENT_REPORT_PDF_DOWNLOADED: "INCIDENT_REPORT_PDF_DOWNLOADED",

  // eMAR (Electronic Medication Administration Record) actions
  EMAR_ORDER_CREATED: "EMAR_ORDER_CREATED",
  EMAR_ORDER_UPDATED: "EMAR_ORDER_UPDATED",
  EMAR_ORDER_DISCONTINUED: "EMAR_ORDER_DISCONTINUED",
  EMAR_ADMINISTERED: "EMAR_ADMINISTERED",
  EMAR_ADMINISTRATION_UPDATED: "EMAR_ADMINISTRATION_UPDATED",
  EMAR_PRN_FOLLOWUP: "EMAR_PRN_FOLLOWUP",
  EMAR_ALERT_ACKNOWLEDGED: "EMAR_ALERT_ACKNOWLEDGED",
  EMAR_SCHEDULES_GENERATED: "EMAR_SCHEDULES_GENERATED",
  EMAR_MAR_REPORT_GENERATED: "EMAR_MAR_REPORT_GENERATED",

  // Progress Note actions
  PROGRESS_NOTE_CREATED: "PROGRESS_NOTE_CREATED",
  PROGRESS_NOTE_UPDATED: "PROGRESS_NOTE_UPDATED",
  PROGRESS_NOTE_GENERATED: "PROGRESS_NOTE_GENERATED",
  PROGRESS_NOTE_FINALIZED: "PROGRESS_NOTE_FINALIZED",
  PROGRESS_NOTE_DELETED: "PROGRESS_NOTE_DELETED",
  PROGRESS_NOTE_PDF_DOWNLOADED: "PROGRESS_NOTE_PDF_DOWNLOADED",

  // Facility Invitation actions
  INVITATION_SENT: "INVITATION_SENT",
  INVITATION_ACCEPTED: "INVITATION_ACCEPTED",
  INVITATION_CANCELLED: "INVITATION_CANCELLED",

  // Care Coordination actions
  CARE_COORDINATION_CREATED: "CARE_COORDINATION_CREATED",
  CARE_COORDINATION_UPDATED: "CARE_COORDINATION_UPDATED",
  CARE_COORDINATION_ARCHIVED: "CARE_COORDINATION_ARCHIVED",
  CARE_COORDINATION_RESTORED: "CARE_COORDINATION_RESTORED",
  CARE_COORDINATION_ATTACHMENT_UPLOADED: "CARE_COORDINATION_ATTACHMENT_UPLOADED",
  CARE_COORDINATION_ATTACHMENT_DELETED: "CARE_COORDINATION_ATTACHMENT_DELETED",
  CARE_COORDINATION_SUMMARY_GENERATED: "CARE_COORDINATION_SUMMARY_GENERATED",
  CARE_COORDINATION_PDF_DOWNLOADED: "CARE_COORDINATION_PDF_DOWNLOADED",
} as const;

export type AuditAction = (typeof AuditActions)[keyof typeof AuditActions];
